# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal C++ Simulation Function
#' 
#' @description
#' Low-level C++ function for running TWoLife simulations. This function is for
#' internal use only - users should use \code{\link{twolife_simulation}} instead.
#' 
#' @param neighbor_radius Radius of density dependence influence
#' @param initial_population_size Number of individuals at start
#' @param vision_angle Angle used for orientation when dispersing
#' @param step_length Distance of dispersal event
#' @param base_dispersal_rate Rate at which individuals disperse
#' @param base_birth_rate Basal birth rate
#' @param base_mortality_rate Basal death rate
#' @param birth_density_slope Slope of birth density dependence
#' @param mortality_density_slope Slope of death density dependence
#' @param habitat Square matrix of environmental values (0=matrix, 1=habitat)
#' @param cell_size Resolution length of pixel side
#' @param density_type Density type (0=global, 1=local)
#' @param matrix_mortality_multiplier Mortality multiplier for matrix
#' @param matrix_dispersal_multiplier Dispersal multiplier for matrix
#' @param initial_placement_mode Initial position mode
#' @param boundary_condition Boundary condition type
#' @param max_events Maximum number of events
#' @param initial_x_coordinates X coordinates of initial individuals
#' @param initial_y_coordinates Y coordinates of initial individuals
#' @param genotype_means Genotypical trait means
#' @param genotype_sds Standard deviations
#' @param mutation_rates Mutation rates
#' @param plasticities Plasticities
#' @param sampling_points Number of sampling points
#' @param neutral_mode Neutral simulation mode
#' @param output_file Optional output file path
#' 
#' @return List containing simulation results
#' 
#' @seealso \code{\link{twolife_simulation}} for the user-friendly interface
#' 
#' @keywords internal
#' @name run_twolife_simulation
NULL

run_twolife_simulation <- function(neighbor_radius, initial_population_size, vision_angle, step_length, base_dispersal_rate, base_birth_rate, base_mortality_rate, birth_density_slope, mortality_density_slope, habitat, cell_size, density_type, matrix_mortality_multiplier, matrix_dispersal_multiplier, initial_placement_mode, boundary_condition, max_events, initial_x_coordinates, initial_y_coordinates, genotype_means, genotype_sds, mutation_rates, plasticities, sampling_points, neutral_mode, output_file = NULL) {
  .Call(`_TWoLife_run_twolife_simulation`, neighbor_radius, initial_population_size, vision_angle, step_length, base_dispersal_rate, base_birth_rate, base_mortality_rate, birth_density_slope, mortality_density_slope, habitat, cell_size, density_type, matrix_mortality_multiplier, matrix_dispersal_multiplier, initial_placement_mode, boundary_condition, max_events, initial_x_coordinates, initial_y_coordinates, genotype_means, genotype_sds, mutation_rates, plasticities, sampling_points, neutral_mode, output_file)
}