# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_twolife_simulation <- function(neighbor_radius, initial_population_size, vision_angle, step_length, base_dispersal_rate, base_birth_rate, base_mortality_rate, birth_density_slope, mortality_density_slope, habitat, cell_size, density_type, matrix_mortality_multiplier, matrix_dispersal_multiplier, initial_placement_mode, boundary_condition, max_events, initial_x_coordinates, initial_y_coordinates, genotype_means, genotype_sds, mutation_rates, plasticities, sampling_points, habitat_selection_temperatures, neutral_mode, history_detail = "standard", master_seed = NULL, output_file = NULL) {
    .Call(`_TWoLife_run_twolife_simulation`, neighbor_radius, initial_population_size, vision_angle, step_length, base_dispersal_rate, base_birth_rate, base_mortality_rate, birth_density_slope, mortality_density_slope, habitat, cell_size, density_type, matrix_mortality_multiplier, matrix_dispersal_multiplier, initial_placement_mode, boundary_condition, max_events, initial_x_coordinates, initial_y_coordinates, genotype_means, genotype_sds, mutation_rates, plasticities, sampling_points, habitat_selection_temperatures, neutral_mode, history_detail, master_seed, output_file)
}

